projects:
  myfirstapp:
    schemaPath: src/main/graphql/schema.json
    includes:
      - src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: src/main/graphql/com/amazonaws/amplify/generated/graphql
